### PR TITLE
Require C++17, port from deprecated qAsConst to std::as_const

### PR DESCRIPTION
**Pull request by dfaure-kdab**

### CODE REVIEW

**Comment by dfaure-kdab** [comment]
@cornelius Looks like something related to `aqt` broke in the CI setup?

**Comment by cornelius** [comment]
Not sure what happened, there don't seem to be any changes to the CI setup.

**Comment by dfaure-kdab** [comment]
@cornelius OK if I merge this?

**Comment by cornelius** [comment]
Yes, please go ahead.

**Pull request merged**
