### PR TITLE
Modernize and fix CI build.yml

### PR DESCRIPTION
**Pull request by dantti**

### CODE REVIEW

**Comment by dantti** [comment]
This is due #55, based on what most KDAB repos have as CI config, at my fork:
 - Linux builds fine wit Qt5 and Qt6
 - macos only Qt6 builds fine, no idea why only qmake fails in macOS for Qt5
 - Windows has link issues, maybe #55 fixes those?
 I guess you can't access https://github.com/dantti/libkode/actions/runs/10002268214 so one would need to allow my PR to run.

**Comment by dantti** [comment]
I could also copy a basic .pre-commit.yml file so that clang-format is run and a few others and you can also enable the pre-commit.ci bot which automatically fixes PR that didn't match clang-format or pre-commit rules...

**Comment by dantti** [comment]
Oh and almost forgot, do you still want to support qmake? else macOS with Qt5 would be fixed :D

**Comment by dfaure-kdab** [comment]
Thanks Daniel.
I can access the run you linked.
I doubt enabling C++17 fixes those link issues, but I don't really know what they are about.
I am personally in favor of dropping qmake support, like many projects are doing, but @cornelius has final say.

**Comment by dantti** [comment]
I took another look at the windows issue and it was because I forgot to add the action that setups the MSVC compiler so it was using mingw, now Windows and macOS have issues only with qmake https://github.com/dantti/libkode/actions/runs/10002268214/job/27647299469
If we drop qmake then all will be green :)

**Comment by dantti** [comment]
Ok, this is the best I could do, originally the build file did not use qmake for Windows, so I made my changes also skip it, I splitted the macOS steps and was able to get more details but so far it seems qmake was not happy finding Qt5 libs.
My guess is that now that GitHub has AppleSilicon hardware qmake will have trouble building for Intel there with Qt5 (Qt6 works), so we either drop qmake or skip Qt5 at macOS/arm

https://github.com/dantti/libkode/actions/runs/10009416585/job/27668273280

**Comment by cornelius** [comment]
> Thanks Daniel. I can access the run you linked. I doubt enabling C++17 fixes those link issues, but I don't really know what they are about. I am personally in favor of dropping qmake support, like many projects are doing, but @cornelius has final say.

I would be fine with dropping qmake support. I don't really have specific requirements for libkode myself, so if it works for you all to drop qmake support, let's do it.

**Comment by dantti** [comment]
done

**Pull request merged**
