### PR TITLE
Implement #pragma once guard generation to headers (fixed #29)

### LINKED ISSUE #29: Add ability to generate headers with #pragma once
We should add an option to being able to generate headers with #pragma once include guard
https://github.com/cornelius/libkode/blob/f4f963664ee6b8b088c3bfd6db19bc64e3833358/code_generation/printer.cpp#L692

It is just a note for myself to not forgot to implement this at some point ;)

### PR DESCRIPTION
**Pull request by martonmiklos**
Title says almost all: now it is going to be possible to generate headers having #pragma once based include.

### CODE REVIEW

**Comment by dfaure-kdab** [comment]
I'm even wondering if this should be configurable at all?

AFAIK `#pragma once` is supported everywhere nowadays, for a long time.

**Comment by martonmiklos** [comment]
> I'm even wondering if this should be configurable at all?
> 
> AFAIK `#pragma once` is supported everywhere nowadays, for a long time.

That's true. KODE/kxml_compiler wise I think we are fine with generating `#pragma once` (at least I am).
If KDSoap/kdwsdl2cpp wise you have no objections I am happy to refactor this PR.

**Comment by dfaure-kdab** [comment]
Yep, I have no objection. All compilers support it (gcc since 3.4, so the C++11 requirement forces it to support it).

**Comment by martonmiklos** [comment]
> Yep, I have no objection. All compilers support it (gcc since 3.4, so the C++11 requirement forces it to support it).

Deal! May I ask for a re-review?

**Pull request merged**
